name: optibox-frontend

services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "${ANGULAR_PORT}:4200"
    volumes:
      - /var/www/OPtiBox/SHOP-STI_Front/certs:/certs:ro
    networks:
      - optibox-shared-network

networks:
  optibox-shared-network:
    external: true
